version: "3"
services:
  app:
    image: node:14.16.0
    working_dir: /app
    volumes:
      - ./:/app
      - ./data/node:/app/node_modules
    ports:
      - 8080:8080
    command: make start
    depends_on:
      - db

  db:
    image: postgres    
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data